name: clean_up_community_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  toasty_box: ^1.0.4
  melos: ^6.3.2
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  patrol: 3.15.2

patrol:
  app_name: Clean Up Community App
  android:
    package_name: com.example.clean_up_community_app
  ios:
    bundle_id: com.example.cleanUpCommunityApp

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env